environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel warn
  - npm i -g npm
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test

build: off
